import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1 className=" text-3xl font-bold ">Next JS Template</h1>
      </main>
    </>
  );
}
